Update api-test.yml

diff --git a/.github/workflows/api-test.yml b/.github/workflows/api-test.yml
--- a/.github/workflows/api-test.yml
+++ b/.github/workflows/api-test.yml
@@ -24,21 +24,32 @@ jobs:
         run: mvn clean test -DsuiteXmlFile=testng.xml
         working-directory: ./Test
 
-      - name: Zip TestNG Report
-        run: zip -r test-report.zip test-output
+      - name: List files for debugging
+        run: ls -R
         working-directory: ./Test
+
+      - name: Zip test output
+        if: success()
+        run: |
+          cd ./Test
+          if [ -d "test-output" ]; then
+            zip -r test-report.zip test-output
+          else
+            echo "test-output directory not found"
+            exit 1
+          fi
 
       - name: Send Test Report via Email
         uses: dawidd6/action-send-mail@v3
         with:
           server_address: smtp.gmail.com
           server_port: 465
+          secure: true
           username: ${{ secrets.EMAIL_USERNAME }}
           password: ${{ secrets.EMAIL_PASSWORD }}
           subject: "OMNI - TestNG API Automation Report"
           to: ayesha.ghaffar@m3tech.com.pk
           from: ${{ secrets.EMAIL_USERNAME }}
-          content_type: text/html
           body: |
             <p>Hi,</p>
             <p>Here is the latest TestNG API Automation report of OMNI Product.</p>
